// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prueba2maya.Models;

#nullable disable

namespace prueba2maya.Migrations
{
    [DbContext(typeof(TiendaContext))]
    partial class TiendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("prueba2maya.Models.AuditoriaInventario", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"), 1L, 1);

                    b.Property<int?>("CantidadAntes")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadDespues")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAuditoria")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("RealizadoPor")
                        .HasColumnType("int");

                    b.HasKey("IdAuditoria")
                        .HasName("PK__Auditori__7FD13FA0179052A6");

                    b.HasIndex("IdProducto");

                    b.HasIndex("RealizadoPor");

                    b.ToTable("AuditoriaInventario");
                });

            modelBuilder.Entity("prueba2maya.Models.CarritoProducto", b =>
                {
                    b.Property<int>("IdCarritoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarritoProducto"), 1L, 1);

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdCarrito")
                        .HasColumnType("int");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdCarritoProducto")
                        .HasName("PK__CarritoP__54956F9CABC715B4");

                    b.HasIndex("IdCarrito");

                    b.HasIndex("IdProducto");

                    b.ToTable("CarritoProductos");
                });

            modelBuilder.Entity("prueba2maya.Models.CarritoVenta", b =>
                {
                    b.Property<int>("IdCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrito"), 1L, 1);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdCarrito")
                        .HasName("PK__CarritoV__8B4A618C18C64FA9");

                    b.HasIndex("IdUsuario");

                    b.ToTable("CarritoVentas");
                });

            modelBuilder.Entity("prueba2maya.Models.CategoriasProducto", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("NombreCategoria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__A3C02A1025C0D3EE");

                    b.ToTable("CategoriasProductos");
                });

            modelBuilder.Entity("prueba2maya.Models.ClientesFrecuente", b =>
                {
                    b.Property<int>("IdClienteFrecuente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClienteFrecuente"), 1L, 1);

                    b.Property<DateTime?>("FechaUltimaCompra")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("PuntosAcumulados")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCompras")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdClienteFrecuente")
                        .HasName("PK__Clientes__FF0AE4DDF4BE9117");

                    b.HasIndex("IdCliente");

                    b.ToTable("ClientesFrecuentes");
                });

            modelBuilder.Entity("prueba2maya.Models.DetallePedido", b =>
                {
                    b.Property<int>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePedido"), 1L, 1);

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDetallePedido")
                        .HasName("PK__DetalleP__48AFFD959C37781C");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("prueba2maya.Models.DetallePedidosProveedore", b =>
                {
                    b.Property<int>("IdDetallePedidoProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePedidoProveedor"), 1L, 1);

                    b.Property<int?>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<int?>("IdPedidoProveedor")
                        .HasColumnType("int");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDetallePedidoProveedor")
                        .HasName("PK__DetalleP__57A1DC0E423A71BD");

                    b.HasIndex("IdPedidoProveedor");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetallePedidosProveedores");
                });

            modelBuilder.Entity("prueba2maya.Models.Envio", b =>
                {
                    b.Property<int>("IdEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnvio"), 1L, 1);

                    b.Property<string>("DireccionEnvio")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EstadoEnvio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int?>("IdSucursalRetiro")
                        .HasColumnType("int");

                    b.HasKey("IdEnvio")
                        .HasName("PK__Envios__B814A62E01D78071");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdSucursalRetiro");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("prueba2maya.Models.HistorialPedido", b =>
                {
                    b.Property<int>("IdHistorialPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorialPedido"), 1L, 1);

                    b.Property<int?>("ActualizadoPor")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoNuevo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaCambio")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int");

                    b.HasKey("IdHistorialPedido")
                        .HasName("PK__Historia__A760BE96637C3350");

                    b.HasIndex("ActualizadoPor");

                    b.HasIndex("IdPedido");

                    b.ToTable("HistorialPedidos");
                });

            modelBuilder.Entity("prueba2maya.Models.HistorialPrecio", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"), 1L, 1);

                    b.Property<DateTime?>("FechaCambio")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioAnterior")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrecioNuevo")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdHistorial")
                        .HasName("PK__Historia__9CC7DBB46DF94462");

                    b.HasIndex("IdProducto");

                    b.ToTable("HistorialPrecios");
                });

            modelBuilder.Entity("prueba2maya.Models.InventarioSucursal", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventario"), 1L, 1);

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int");

                    b.HasKey("IdInventario")
                        .HasName("PK__Inventar__1927B20C63A0F4C9");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSucursal");

                    b.ToTable("InventarioSucursal");
                });

            modelBuilder.Entity("prueba2maya.Models.ModosPago", b =>
                {
                    b.Property<int>("IdModoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModoPago"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdModoPago")
                        .HasName("PK__ModosPag__8E18FA0717520843");

                    b.ToTable("ModosPago");
                });

            modelBuilder.Entity("prueba2maya.Models.Oferta", b =>
                {
                    b.Property<int>("IdOferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOferta"), 1L, 1);

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal?>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdOferta")
                        .HasName("PK__Ofertas__5420E1DA0345650F");

                    b.HasIndex("IdProducto");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("prueba2maya.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"), 1L, 1);

                    b.Property<string>("DireccionEntrega")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("FechaPedido")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("MetodoEntrega")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedido")
                        .HasName("PK__Pedidos__9D335DC3C4C6562F");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("prueba2maya.Models.PedidosProveedore", b =>
                {
                    b.Property<int>("IdPedidoProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedidoProveedor"), 1L, 1);

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaPedido")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.HasKey("IdPedidoProveedor")
                        .HasName("PK__PedidosP__B39B8E6CFE017008");

                    b.HasIndex("IdProveedor");

                    b.ToTable("PedidosProveedores");
                });

            modelBuilder.Entity("prueba2maya.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"), 1L, 1);

                    b.Property<int?>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreProducto")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__09889210B1A16AC8");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("prueba2maya.Models.Proveedore", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"), 1L, 1);

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreProveedor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdProveedor")
                        .HasName("PK__Proveedo__E8B631AF2020BC4F");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("prueba2maya.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"), 1L, 1);

                    b.Property<string>("NombreRol")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__2A49584C43E7FF9E");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("prueba2maya.Models.Sucursale", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSucursal"), 1L, 1);

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreSucursal")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdSucursal")
                        .HasName("PK__Sucursal__BFB6CD99B5C1F8FC");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("prueba2maya.Models.TransaccionesPago", b =>
                {
                    b.Property<int>("IdTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransaccion"), 1L, 1);

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaTransaccion")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdModoPago")
                        .HasColumnType("int");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdTransaccion")
                        .HasName("PK__Transacc__334B1F77AA49818C");

                    b.HasIndex("IdModoPago");

                    b.HasIndex("IdPedido");

                    b.ToTable("TransaccionesPagos");
                });

            modelBuilder.Entity("prueba2maya.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Contrasena")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__5B65BF972B27845D");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__A9D10534F58AAA08")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("prueba2maya.Models.AuditoriaInventario", b =>
                {
                    b.HasOne("prueba2maya.Models.Producto", "IdProductoNavigation")
                        .WithMany("AuditoriaInventarios")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Auditoria__IdPro__6FE99F9F");

                    b.HasOne("prueba2maya.Models.Usuario", "RealizadoPorNavigation")
                        .WithMany("AuditoriaInventarios")
                        .HasForeignKey("RealizadoPor")
                        .HasConstraintName("FK__Auditoria__Reali__70DDC3D8");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("RealizadoPorNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.CarritoProducto", b =>
                {
                    b.HasOne("prueba2maya.Models.CarritoVenta", "IdCarritoNavigation")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("IdCarrito")
                        .HasConstraintName("FK__CarritoPr__IdCar__52593CB8");

                    b.HasOne("prueba2maya.Models.Producto", "IdProductoNavigation")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__CarritoPr__IdPro__534D60F1");

                    b.Navigation("IdCarritoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.CarritoVenta", b =>
                {
                    b.HasOne("prueba2maya.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("CarritoVenta")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__CarritoVe__IdUsu__4F7CD00D");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.ClientesFrecuente", b =>
                {
                    b.HasOne("prueba2maya.Models.Usuario", "IdClienteNavigation")
                        .WithMany("ClientesFrecuentes")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__ClientesF__IdCli__693CA210");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.DetallePedido", b =>
                {
                    b.HasOne("prueba2maya.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdPedido")
                        .HasConstraintName("FK__DetallePe__IdPed__59FA5E80");

                    b.HasOne("prueba2maya.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__DetallePe__IdPro__5AEE82B9");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.DetallePedidosProveedore", b =>
                {
                    b.HasOne("prueba2maya.Models.PedidosProveedore", "IdPedidoProveedorNavigation")
                        .WithMany("DetallePedidosProveedores")
                        .HasForeignKey("IdPedidoProveedor")
                        .HasConstraintName("FK__DetallePe__IdPed__4BAC3F29");

                    b.HasOne("prueba2maya.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetallePedidosProveedores")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__DetallePe__IdPro__4CA06362");

                    b.Navigation("IdPedidoProveedorNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.Envio", b =>
                {
                    b.HasOne("prueba2maya.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("Envios")
                        .HasForeignKey("IdPedido")
                        .HasConstraintName("FK__Envios__IdPedido__6C190EBB");

                    b.HasOne("prueba2maya.Models.Sucursale", "IdSucursalRetiroNavigation")
                        .WithMany("Envios")
                        .HasForeignKey("IdSucursalRetiro")
                        .HasConstraintName("FK__Envios__IdSucurs__6D0D32F4");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdSucursalRetiroNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.HistorialPedido", b =>
                {
                    b.HasOne("prueba2maya.Models.Usuario", "ActualizadoPorNavigation")
                        .WithMany("HistorialPedidos")
                        .HasForeignKey("ActualizadoPor")
                        .HasConstraintName("FK__Historial__Actua__74AE54BC");

                    b.HasOne("prueba2maya.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("HistorialPedidos")
                        .HasForeignKey("IdPedido")
                        .HasConstraintName("FK__Historial__IdPed__73BA3083");

                    b.Navigation("ActualizadoPorNavigation");

                    b.Navigation("IdPedidoNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.HistorialPrecio", b =>
                {
                    b.HasOne("prueba2maya.Models.Producto", "IdProductoNavigation")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Historial__IdPro__6383C8BA");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.InventarioSucursal", b =>
                {
                    b.HasOne("prueba2maya.Models.Producto", "IdProductoNavigation")
                        .WithMany("InventarioSucursals")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Inventari__IdPro__44FF419A");

                    b.HasOne("prueba2maya.Models.Sucursale", "IdSucursalNavigation")
                        .WithMany("InventarioSucursals")
                        .HasForeignKey("IdSucursal")
                        .HasConstraintName("FK__Inventari__IdSuc__45F365D3");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.Oferta", b =>
                {
                    b.HasOne("prueba2maya.Models.Producto", "IdProductoNavigation")
                        .WithMany("Oferta")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Ofertas__IdProdu__66603565");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.Pedido", b =>
                {
                    b.HasOne("prueba2maya.Models.Sucursale", "IdSucursalNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdSucursal")
                        .HasConstraintName("FK__Pedidos__IdSucur__571DF1D5");

                    b.HasOne("prueba2maya.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Pedidos__IdUsuar__5629CD9C");

                    b.Navigation("IdSucursalNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.PedidosProveedore", b =>
                {
                    b.HasOne("prueba2maya.Models.Proveedore", "IdProveedorNavigation")
                        .WithMany("PedidosProveedores")
                        .HasForeignKey("IdProveedor")
                        .HasConstraintName("FK__PedidosPr__IdPro__48CFD27E");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.Producto", b =>
                {
                    b.HasOne("prueba2maya.Models.CategoriasProducto", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK__Productos__IdCat__403A8C7D");

                    b.HasOne("prueba2maya.Models.Proveedore", "IdProveedorNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .HasConstraintName("FK__Productos__IdPro__4222D4EF");

                    b.HasOne("prueba2maya.Models.Sucursale", "IdSucursalNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdSucursal")
                        .HasConstraintName("FK__Productos__IdSuc__412EB0B6");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdProveedorNavigation");

                    b.Navigation("IdSucursalNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.TransaccionesPago", b =>
                {
                    b.HasOne("prueba2maya.Models.ModosPago", "IdModoPagoNavigation")
                        .WithMany("TransaccionesPagos")
                        .HasForeignKey("IdModoPago")
                        .HasConstraintName("FK__Transacci__IdMod__60A75C0F");

                    b.HasOne("prueba2maya.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("TransaccionesPagos")
                        .HasForeignKey("IdPedido")
                        .HasConstraintName("FK__Transacci__IdPed__5FB337D6");

                    b.Navigation("IdModoPagoNavigation");

                    b.Navigation("IdPedidoNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.Usuario", b =>
                {
                    b.HasOne("prueba2maya.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__Usuarios__IdRol__02084FDA");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("prueba2maya.Models.CarritoVenta", b =>
                {
                    b.Navigation("CarritoProductos");
                });

            modelBuilder.Entity("prueba2maya.Models.CategoriasProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("prueba2maya.Models.ModosPago", b =>
                {
                    b.Navigation("TransaccionesPagos");
                });

            modelBuilder.Entity("prueba2maya.Models.Pedido", b =>
                {
                    b.Navigation("DetallePedidos");

                    b.Navigation("Envios");

                    b.Navigation("HistorialPedidos");

                    b.Navigation("TransaccionesPagos");
                });

            modelBuilder.Entity("prueba2maya.Models.PedidosProveedore", b =>
                {
                    b.Navigation("DetallePedidosProveedores");
                });

            modelBuilder.Entity("prueba2maya.Models.Producto", b =>
                {
                    b.Navigation("AuditoriaInventarios");

                    b.Navigation("CarritoProductos");

                    b.Navigation("DetallePedidos");

                    b.Navigation("DetallePedidosProveedores");

                    b.Navigation("HistorialPrecios");

                    b.Navigation("InventarioSucursals");

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("prueba2maya.Models.Proveedore", b =>
                {
                    b.Navigation("PedidosProveedores");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("prueba2maya.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("prueba2maya.Models.Sucursale", b =>
                {
                    b.Navigation("Envios");

                    b.Navigation("InventarioSucursals");

                    b.Navigation("Pedidos");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("prueba2maya.Models.Usuario", b =>
                {
                    b.Navigation("AuditoriaInventarios");

                    b.Navigation("CarritoVenta");

                    b.Navigation("ClientesFrecuentes");

                    b.Navigation("HistorialPedidos");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
